language: node_js
node_js:
  - "10.13.0"

services:
  - docker

before_install:
  - rm -rf dist/*
  - npm install -g npx
  - npm install -q
script:
  - npm run build:prod
  - npm run test

notifications:
  email:
    on_success: never
