language: node_js
node_js:
  - "6.11.4"
  - "8.12.0"
  - "10.1.0"

cache:
  directories:
    - "node_modules"

services:
  - docker

before_install:
  - rm -rf dist/*
  - npm install -g gulp
  - npm install -q

script:
  - npm run test

after_script:
  - pip install --user codecov
  - codecov --file coverage/lcov.info --disable search

notifications:
  email:
    on_success: never
